#!/bin/bash

# Deploy Brastel PIN Checker to Multiple VPS
# Usage: ./deploy-vps.sh

echo "🚀 Deploying Brastel PIN Checker to Multiple VPS"
echo "=================================================="

# Configuration - Edit these values for your setup
VPS_LIST=(
    "user@192.168.1.10"
    "user@192.168.1.11"
    "user@192.168.1.12"
    "user@192.168.1.13"
    "user@192.168.1.14"
)

VPS_IPS=(
    "192.168.1.10"
    "192.168.1.11"
    "192.168.1.12"
    "192.168.1.13"
    "192.168.1.14"
)

TOTAL_SERVERS=${#VPS_LIST[@]}
PORT=3000
REMOTE_PATH="~/BrastelPin"

echo "📊 Total Servers: $TOTAL_SERVERS"
echo "📦 Remote Path: $REMOTE_PATH"
echo "🌐 Port: $PORT"
echo ""

# Function to create .env file content
create_env_file() {
    local server_id=$1
    local env_content="# Generated by deploy-vps.sh
SERVER_ID=$server_id
TOTAL_SERVERS=$TOTAL_SERVERS
PORT=$PORT

"

    # Add all server addresses
    for i in "${!VPS_IPS[@]}"; do
        local sid=$((i + 1))
        env_content+="SERVER_${sid}_ADDRESS=http://${VPS_IPS[$i]}:$PORT"$'\n'
    done

    echo "$env_content"
}

# Deploy to each VPS
for i in "${!VPS_LIST[@]}"; do
    VPS=${VPS_LIST[$i]}
    SERVER_ID=$((i + 1))

    echo "🎯 Deploying to Server $SERVER_ID: $VPS"
    echo "----------------------------------------"

    # Create remote directory
    echo "📁 Creating remote directory..."
    ssh $VPS "mkdir -p $REMOTE_PATH"

    # Copy project files (excluding node_modules, logs, data)
    echo "📋 Copying project files..."
    rsync -avz --exclude 'node_modules' --exclude 'Log' --exclude 'Data' --exclude '*.log' --exclude '.git' ./ $VPS:$REMOTE_PATH/

    # Create .env file
    echo "⚙️  Creating .env file..."
    create_env_file $SERVER_ID | ssh $VPS "cat > $REMOTE_PATH/.env"

    # Install dependencies
    echo "📦 Installing dependencies..."
    ssh $VPS "cd $REMOTE_PATH && npm install"

    # Stop existing process
    echo "🛑 Stopping existing processes..."
    ssh $VPS "pkill -f 'node.*web-gui' || true"

    # Start new process
    echo "🚀 Starting server..."
    ssh $VPS "cd $REMOTE_PATH && nohup node start-servers.js > server.log 2>&1 &"

    echo "✅ Server $SERVER_ID deployed successfully"
    echo ""

    # Wait a bit before next server
    sleep 2
done

echo "🎉 Deployment completed!"
echo "======================="
echo ""
echo "🌐 Access URLs:"
for i in "${!VPS_IPS[@]}"; do
    server_id=$((i + 1))
    ip=${VPS_IPS[$i]}
    echo "   Server $server_id: http://$ip:$PORT"
    echo "   Queue Manager $server_id: http://$ip:$PORT/process-queue.html"
done

echo ""
echo "📋 Next Steps:"
echo "1. Wait a few minutes for all servers to start"
echo "2. Access any server web interface"
echo "3. Create a new process - it will distribute across all servers"
echo "4. Monitor logs: ssh user@server-ip 'tail -f ~/BrastelPin/server.log'"
echo ""
echo "🔧 Troubleshooting:"
echo "- Check server logs: ssh user@server-ip 'cat ~/BrastelPin/server.log'"
echo "- Check process status: curl http://server-ip:$PORT/api/queue-status"
echo "- Restart server: ssh user@server-ip 'cd ~/BrastelPin && pkill -f node && nohup node start-servers.js > server.log 2>&1 &'"